# Settings for Snake Game. Changes the Algorithm, Game Mechanics, Model Layout, etc.

# Game Mechanics
CANV_WIDTH = 600
CANV_HEIGHT = 600
ROWS = 3
COLUMNS = 3 
BG_COLOR = (51, 51, 51)
GAME_FPS = 10

SNAKE_WIDTH = CANV_WIDTH / (ROWS + 1)
KEYBOARD_ENABLED = True

# AI Algorithm
NUM_INPUTS = 28
WEIGHTS = [NUM_INPUTS, 24, 16, 3]

#Genetic Algorithm
NUM_POP = 100
NUM_GENERATIONS = 1000
NUM_ELITES = 10
NUM_MUTATIONS = 10
MUTATE_RATE = 0.5
RUN_GEN_WITH_PYGAME = True
PYGAME_LOOK_GEN = 50
STEPS = 30
STEPS_ENABLED = True
SCORE_INC = 10
STAT_INC = 0.001
STEP_INC_SCORE = 20